export { default as Home } from './Home'
export { default as About } from './About'
export { default as MarketPlace } from './MarketPlace'
export { default as WhitePaper } from './WhitePaper'
export { default as Tokenomics } from './Tokenomics'